/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentStatusType = "CANCELLED" | "COMPLETED" | "DIDNTSHOW" | "SCHEDULED";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type RoleType = "ADMIN" | "DOCTOR" | "LAB_NURSE" | "LAB_TECHNICIAN" | "PATIENT";

export type SchedulableType = "DOCTOR";

export type ShiftType = "EVENING" | "MORNING";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WeekdayType = "FRIDAY" | "MONDAY" | "SATURDAY" | "SUNDAY" | "THURSDAY" | "TUESDAY" | "WEDNESDAY";

export interface AcademicRecord {
  degree: string;
  doctor_profile_id: number;
  id: Generated<number>;
  institute: string;
  year: Timestamp;
}

export interface Appointment {
  date: Timestamp;
  end_time: string;
  id: Generated<number>;
  patient_id: number;
  schedule_id: number;
  shift: ShiftType;
  start_time: string;
  status: AppointmentStatusType;
  uuid: Generated<string>;
}

export interface Complaint {
  id: Generated<number>;
  name: string;
  uuid: Generated<string>;
}

export interface Department {
  id: Generated<number>;
  name: string;
  uuid: Generated<string>;
}

export interface DoctorExperience {
  doctor_profile_id: number;
  end_year: Timestamp | null;
  id: Generated<number>;
  location: string | null;
  organization: string;
  start_year: Timestamp;
  title: string;
}

export interface DoctorProfile {
  department_id: number | null;
  id: Generated<number>;
  scheduleId: number | null;
  user_id: number;
}

export interface RefreshToken {
  expires_at: Timestamp;
  id: Generated<number>;
  jit: string;
  token_hash: string;
  user_id: number;
}

export interface Routine {
  end_time: string;
  id: Generated<number>;
  schedule_id: number;
  shift: ShiftType;
  start_time: string;
  week_day: WeekdayType;
}

export interface Schedule {
  entity_id: number;
  id: Generated<number>;
  max_booking_days: number;
  minutes_per_slot: number;
  type: SchedulableType;
  uuid: Generated<string>;
}

export interface UserAccount {
  birth_date: Timestamp;
  email: string;
  id: Generated<number>;
  name: string;
  password_hash: string;
  uuid: Generated<string>;
}

export interface UserRole {
  id: Generated<number>;
  role: RoleType;
  user_id: number;
}

export interface DB {
  academic_record: AcademicRecord;
  appointment: Appointment;
  complaint: Complaint;
  department: Department;
  doctor_experience: DoctorExperience;
  doctor_profile: DoctorProfile;
  refresh_token: RefreshToken;
  routine: Routine;
  schedule: Schedule;
  user_account: UserAccount;
  user_role: UserRole;
}
